### ISSUE TITLE
Doppelte Abschnitte in Kundencenter-Dokumentation

### ISSUE THREAD

**Issue by patrickhilker** [mittwald/developer-portal#103]
Auf https://developer.mittwald.de/reference/v1/ sind die ersten drei Punkte dreifach vorhanden und teilweise leer und teilweise unterschiedlich.

- Authentifizierung
- Rate Limiting
- Caching

![image](https://github.com/mittwald/developer-portal/assets/5042280/2e1e1764-9bda-4122-bfff-76bb610af1c8)

**Comment by martin-helmich** [comment]
Fixed with #94
