### ISSUE TITLE
Add color coding to routes in tag overview

### ISSUE THREAD

**Issue by LukasFritzeDev** [mittwald/developer-portal#121]
In the sidebar navigation routes are color coded depending on der HTTP method. When showing a Tag overview (example [All app routes](https://developer.mittwald.de/docs/v2/reference/app/)) they are not. Therefore the route list in the content area is much less helpful than it could be.

![image](https://github.com/mittwald/developer-portal/assets/12097997/38fe4fa4-d8fa-401f-af76-518b0a236325)

**Comment by martin-helmich** [comment]
Full ack; unfortunately, the auto-generated category index pages are not as easy to customize as the sidebar. This could probably be done by swizzling the DocCard component and adding some custom logic to it; I'll do some reading on this.
