### ISSUE TITLE
Suchfunktion hinzufügen

### ISSUE THREAD

**Issue by TanjaOffers** [mittwald/developer-portal#172]
Aktuell gibt es noch keine Suchfunktion nach Stichworten. 
Die würde ich mir für das Arbeiten mit der Doku wünschen.

**Comment by martin-helmich** [comment]
Das ist nicht ganz trivial, da Docusaurus ja lediglich eine statische HTML-Site produziert. Üblicherweise läuft das über Drittanbieter-Integrationen ([siehe Doku](https://docusaurus.io/docs/search)).

Es gibt bereits Bemühungen, einen LLM-basierten Suchassistenten für das Dev-Portal zu bauen ([interner Link](https://gitlab.mittwald.it/coab-0x7e7/guilds/developer-experience/inbox/-/issues/14)). Da das Thema sowieso läuft, würde ich die klassische Suchfunktion erstmal zugunsten dessen hinten anstellen.

**Comment by martin-helmich** [comment]
> Das Thema LLM-Suche ist noch nicht weiter gegangen. Wir brauchen aber für die Extension-Doku definitiv langsam eine Suchfunktion. Klar wäre LLM cool, aber ne einfache Suche würde auch schon mal helfen. Die Doku wird im nächsten Monat nochmal um ein paar Seiten und Querverweise erweitert. Eine Suche ist mittlerweile nicht mehr nur noch nice to have, sondern Essenziell.

Ab nächstem Jahr gibt es ein dediziertes Developer Relations-Team; ich nehme das Thema nochmal mit, womöglich haben wir ab dann mehr Kapazitäten, das nochmal aufzugreifen.
