### ISSUE TITLE
API-Doku Aufschlüsseln

### ISSUE THREAD

**Issue by TanjaOffers** [mittwald/developer-portal#183]
Kann man das so hin bekommen, dass die Änderungen direkt einsehbar sind? Also als (ggf. durchsuchbare) Liste? 

Aktuell sehe ich erstmal nur zu groß geratene Überschriften, jedes mal den gleichen Text und wenn ich wissen will, was wirklich passiert ist, muss ich jeden Artikel öffnen.

![image](https://github.com/user-attachments/assets/f94fd1cf-b3fa-4ba7-b3c7-c0864263b54b)

**Comment by martin-helmich** [comment]
Behoben mit #192; die Teaser-Texte werden nun (zukünftig) dynamisch aus den jeweiligen Changes generiert, und sollten die tatsächlich stattgefundenen API-Änderungen knapp zusammenfassen.

Für bereits generierte Changelog-Einträge müsste der Einleitungstext jeweils von Hand angepasst werden, sofern gewünscht.
