### ISSUE TITLE
Wrong array key used in redis TYPO3 example

### ISSUE THREAD

**Issue by rteitge** [mittwald/developer-portal#271]
### Affected URL

https://developer.mittwald.de/de/docs/v2/platform/databases/redis/#typo3

### Describe the issue

This section in TYPO3 example
```php
if (isset($values['defaultLifetime'])) {
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['caching']['cacheConfigurations'][$name]['options']['defaultLifetime'] = $values['lifetime'];
}
```
uses the array key `liftime`, but there is only a `defaultLifetime` key in `$redisCaches` array so this code will result in an exception `The default lifetime must be given as a positive integer. | InvalidArgumentException`.

**Comment by martin-helmich** [comment]
Thanks for the report, good catch! :+1:  Opened #274 to fix this.
